### ISSUE TITLE
ch15 - deprecated apiVersion for ingress object

### ISSUE THREAD

**Issue by nicolimo86** [sixeyed/kiamol#32]
Hello,
in ch15 the manifests for the ingress object have the deprecated value `networking.k8s.io/v1beta1`. This makes them failing on kubernetes servers with version 1.18 or newer.

The correct apiVersion is now `"apiVersion: networking.k8s.io/v1"`

**Comment by WriterOfAlicrow** [comment]
This is not just in chapter 15. Throughout the book, yaml files are using beta api versions that no longer exist. Changing it to "v1" usually seems to solve the issue.
However, the nginx ingress configuration requires further changes, because the container itself tries to use the deprecated api, even if the manifests are updated to the correct api version.

**Comment by nicolimo86** [comment]
@WriterOfAlicrow correct, many things are already different. I tried to change the manifests for chapter 15. I tested several of them, and they seem to work now.

**Comment by WriterOfAlicrow** [comment]
I managed to get this to work, at least for the hello-kiamol app (haven't tested the others yet), but it required some changes beyond what @nicolimo86 needed. I'm running kubernetes 1.22, which I think removed or changed more things.

In the Ingress definition files I had to:
* Update the apiVersions to `v1`
* Change `serviceName` and `servicePort` to `service.name` and `service.port.number`
* add `pathType: Prefix` to the path specification
* add `annotations: kubernetes.io/ingress.class: "nginx"` to the metadata

In `nginx-ingress-controller.yaml`, I had to:
* Update the image version to `k8s.gcr.io/ingress-nginx/controller:v1.1.1@sha256:0bc88eb15f9e7f84e8e56c14fa5735aaa488b840983f87bd79b1054190e660de` so it uses the right API version
* Change `ingress-controller-leader-nginx` to `ingress-controller-leader` in the `Role` specification so it had access to update the right resource.
* Add an IngressClass specification at the bottom on the file containing:
```yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: nginx
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx
```
