### ISSUE TITLE
Ch03 - Basic service is not working as expected.

### ISSUE THREAD

**Issue by realalien** [sixeyed/kiamol#59]
After creating a service with following code,  
```
apiVersion: v1
kind: Service
metadata:
  name: sleep-2
spec:
  selector:
    app: sleep-2
  ports:
    - port: 80
```
the command `kubectl exec deploy/sleep-1 -- ping -c 1 sleep-2` will throw error like `ping: bad address 'sleep-2' command terminated with exit code 1
`, 
while the `kubectl exec deploy/sleep-1 -- ping -c 2 $(kubectl get pod -l app=sleep-2 --output jsonpath='{.items[0].status.podIP}')` works just fine.

The manual of Kubernetes Service is hard to digest for noobie like me, what's the cause?
